package com.example.demo.restservice.RestApp;


import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

@Controller    // This means that this class is a Controller
@RequestMapping(path = "/records")
public class MainController {
    @Autowired// This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private RecordRepository RecordRepository;

    @GetMapping(path = "/add") // Map ONLY GET Requests
    public @ResponseBody
    String addNewRecord(@RequestParam String type, @RequestParam String slotContent, @RequestParam String slotDesc,
                        @RequestParam String slotSentence) {

        Record n = new Record();
        n.setType(type);
        n.setSlotContent(slotContent);
        n.setSlotDesc(slotDesc);
        n.setSlotSentence(slotSentence);
        RecordRepository.save(n);
        return "com.example.demo.restservice.RestApp.RestApp.Record Saved";
    }


}
